@startuml erd
title ER
entity Member {
  * memberId(pk)
  --
  voicechannelId(fk)
}
entity VC {
  * voicechannelId(pk)
  --
  privateChannelId(fk)
}
entity PrivateChannel {
  * id(pk)
  --
  roleId
  textchannelId
}
entity BotMessage {
  * id(pk)
  --
  * key
  content
  file
  enable
  createrId(fk)
}
PrivateChannel ||--|| VC
Member }o--|| VC
@enduml